apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dotnetapi
  name: dotnetapi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetapi
  name: dotnetapi
  namespace: dotnetapi
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dotnetapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnetapi
  name: dotnetapi
  namespace: dotnetapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapi
  template:
    metadata:
      labels:
        app: dotnetapi
    spec:
      containers:
      - image: dotnetaksdemo.azurecr.io/dotnetapi-aks-app:51f11a686d810e83cae84c66e7c27a09a097627b
        name: dotnetapi-aks-app
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
