apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dotnetapi
  name: dotnetapi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetapi
  name: dotnetapi
  namespace: dotnetapi
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: dotnetapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnetapi
  name: dotnetapi
  namespace: dotnetapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapi
  template:
    metadata:
      labels:
        app: dotnetapi
    spec:
      containers:
      - image: yemiwebby/dotnetapi-aks-app:720a4f0b35c91b05b0ac810112e792917be89b04
        name: dotnetapi-aks-app
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        kubernetes.io/os: windows
