apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: dotnetapi
images:
- name: dotnetapi-aks-app
  newName: yemiwebby/dotnetapi-aks-app
  newTag: f7f9788be33e020eccd99f4f8c335bc037251ff9
