apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: dotnetapi
images:
- name: dotnetapi-aks-app
  newName: dotnetaksdemo.azurecr.io/dotnetapi-aks-app
  newTag: 98be40c2de8dc35f799fd1c5b01e800c80429dc4
