apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: dotnetapi
images:
- name: dotnetapi-aks-app
  newName: yemiwebby/dotnetapi-aks-app
  newTag: 921f5bf68a42145e669ccb6f50e1035a8794bf7e
